<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="P_edit_program.aspx.cs" Inherits="WebApplication1.P_edit_program" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h4>Редактор программы</h4>
    <p>Вы можете добавить любую программу к выбранному туру (соершите выбор в списке ниже)</p>
    <p>Редактировать тур:</p>
    <asp:DropDownList ID="DropDownList_tour_select_id" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource1" DataTextField="name_tour" DataValueField="id_tour" OnSelectedIndexChanged="DropDownList_tour_select_id_SelectedIndexChanged"></asp:DropDownList>
    <asp:SqlDataSource  ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:tour_firmConnectionString %>" SelectCommand="SELECT [id_tour], [name_tour] FROM [tour]"></asp:SqlDataSource> 
    
    <table>
        <tr><td >Номер посещения</td> <td><asp:TextBox ID="TextBox_numer_list" runat="server"></asp:TextBox></td></tr>
        <tr><td> Дней на месте</td><tb>
            <td><asp:TextBox ID="TextBox_numero_dey" runat="server"></asp:TextBox></td>
            </tb></tr>
        <tr><td>Отель</td><td><asp:DropDownList ID="DropDownList_hotel" runat="server" DataSourceID="SqlDataSource4" DataTextField="name_hotel" DataValueField="id_hotel" OnSelectedIndexChanged="DropDownList_hotel_SelectedIndexChanged"></asp:DropDownList>
                <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:tour_firmConnectionString %>" SelectCommand="SELECT [id_hotel], [name_hotel] FROM [hotel]"></asp:SqlDataSource></td></tr>
    </table>
    <br />
    <asp:Button ID="Button_add_program" runat="server" Text="Добавить" OnClick="Button_add_program_Click" />
    <br />
    <asp:Label ID="Label_error_add" runat="server" Visible="false" Text="error"></asp:Label>
    <br />
    <asp:Label ID="Label_numer_day_all" runat="server" Text="Общая продложительность тура: 15 дней"></asp:Label>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="id_program" DataSourceID="SqlDataSource2" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
        <Columns>
            <asp:BoundField DataField="id_program" HeaderText="id_program" ReadOnly="True" SortExpression="id_program" InsertVisible="False" />
            <asp:BoundField DataField="numer_list" HeaderText="numer_list" SortExpression="numer_list" />
            <asp:BoundField DataField="numer_day" HeaderText="numer_day" SortExpression="numer_day" />
            <asp:BoundField DataField="id_hotel" HeaderText="id_hotel" SortExpression="id_hotel" />
            <asp:BoundField DataField="name_hotel" HeaderText="name_hotel" ReadOnly="True"  SortExpression="name_hotel" />
            <asp:BoundField DataField="id_tour" HeaderText="id_tour"  SortExpression="id_tour" />
            <asp:BoundField DataField="name_tour" HeaderText="name_tour" ReadOnly="True"  SortExpression="name_tour" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:tour_firmConnectionString %>" SelectCommand="SELECT program_tour.id_program, program_tour.numer_list, program_tour.numer_day, program_tour.id_hotel, hotel.name_hotel, program_tour.id_tour, tour.name_tour FROM hotel JOIN program_tour ON hotel.id_hotel = program_tour.id_hotel JOIN tour ON program_tour.id_tour = tour.id_tour  WHERE program_tour.id_tour=@id_tour" DeleteCommand="DELETE FROM program_tour where program_tour.id_program=@id_program" UpdateCommand="UPDATE program_tour SET numer_list =@numer_list , numer_day =@numer_day , id_hotel =@id_hotel , id_tour=@id_tour where id_program=@id_program">
        <UpdateParameters>
            <asp:SessionParameter Name="id_program" SessionField="ID_id_program_tour" Type="Int32" />
        </UpdateParameters>
        <DeleteParameters>
            <asp:SessionParameter Name="id_program" SessionField="ID_id_program_tour" Type="Int32"/>
        </DeleteParameters>
        <SelectParameters>
            <asp:SessionParameter DefaultValue="1" Name="id_tour" SessionField="ID_tour" Type="Int32"/>
        </SelectParameters>
        <UpdateParameters>
            <asp:SessionParameter Name="numer_list" SessionField="numer_list" Type="Int32"/>
            <asp:SessionParameter Name="numer_day" SessionField="numer_day" Type="Int32"/>
            <asp:SessionParameter Name="id_hotel" SessionField="id_hotel" Type="Int32"/>
            <asp:SessionParameter Name="id_tour" SessionField="id_tour" Type="Int32"/>
        </UpdateParameters>
    </asp:SqlDataSource>
</asp:Content>
