<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="P_new_profil_maker.aspx.cs" Inherits="WebApplication1.P_new_profil_maker" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h3>Создание профилей</h3>
    <p>При создании новых профелей сотрудников будте внимательны и не забывайте пароль и логин – редакция без доступа к базе данных или самому акаунту недоступна.</p>
    <table border="0">
        <tr>
            <td>
                <p>Имя</p> 
            </td>
            <td>
                <asp:TextBox ID="TextBox_first_name" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>
                <p>Фамилия</p> 
            </td>
            <td>
                <asp:TextBox ID="TextBox_last_name" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>
                <p>Очество</p>
            </td>
            <td>
                <asp:TextBox ID="TextBox_surname" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>
                <p>Роль (1-Админ\2-Менеджер)</p>
            </td>
            <td>
                <asp:TextBox ID="TextBox_role" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>
                <p>Номер телефона</p>
            </td>
            <td>
                <asp:TextBox ID="TextBox_numer_telephone" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>
                <p>Почта (email)</p>
            </td>
            <td>
                <asp:TextBox ID="TextBox_email" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>
                <p>Логин</p>
            </td>
            <td>
                <asp:TextBox ID="TextBox_login" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td>
                <p>Пароль  </p>
            </td>
            <td>
                <asp:TextBox ID="TextBox_password" runat="server"></asp:TextBox>
            </td>
        </tr>
    </table>  
    <h4><asp:Label ID="Label_insert" Visible="false" runat="server" Text="Ошибка при добавлении!"></asp:Label></h4> 
    <asp:Button ID="Button_edit" runat="server" Text="Добавить" OnClick="Button1_Click" />    
    <h2>Полный список пользователей:</h2>
    <p>Здесь же имеется возможность удалить пользователей при необходимости. Отмена невозможна! </p>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="id_user" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged1" AllowPaging="True">
        <Columns>
            <asp:BoundField DataField="id_user" HeaderText="ID пользователя" InsertVisible="False" ReadOnly="True" SortExpression="id_user" />
            <asp:BoundField DataField="pasword" HeaderText="Пароль" SortExpression="pasword" />
            <asp:BoundField DataField="login" HeaderText="Логин" SortExpression="login" />
            <asp:BoundField DataField="mail" HeaderText="Почта" SortExpression="mail" />
            <asp:BoundField DataField="numer_telephone" HeaderText="Номер телефона" SortExpression="numer_telephone" />
            <asp:BoundField DataField="id_role" HeaderText="Тип роли" SortExpression="id_role" />
            <asp:BoundField DataField="last_name" HeaderText="Имя" SortExpression="last_name" />
            <asp:BoundField DataField="first_name" HeaderText="Фамилия" SortExpression="first_name" />
            <asp:BoundField DataField="surname" HeaderText="Очество" SortExpression="surname" />
        </Columns>
    </asp:GridView>
    
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:tour_firmConnectionString %>" DeleteCommand="DELETE FROM [t_user] WHERE id_user=@id_user" SelectCommand="SELECT * from t_user">
        <DeleteParameters>
            <asp:SessionParameter DefaultValue="0" Name="id_user" SessionField="ID_user_deleted" Type="Int32"/>
        </DeleteParameters>
    </asp:SqlDataSource>
    
</asp:Content>
